development:
  adapter: postgresql
  encoding: unicode
  database: lolchat_development
  pool: 5
  min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: lolchat_test
  pool: 5
  min_messages: notice
